

const env = process.env

const config = {
  PORT: env.PORT || 5010,
  AUTH_JWT_SECRET: env.ICEPICK_AUTH_JWT_SECRET,
  FILE_JWT_SECRET: env.ICEPICK_FILE_JWT_SECRET,
  THUMB_DIM: env.ICEPICK_THUMB_DIM || 256,
  SQUARE_DIM: env.ICEPICK_SQUARE_DIM || 512,
  BACKGROUND_DIM_X: env.ICEPICK_BACKGROUND_DIM_X || 1500,
  BACKGROUND_DIM_Y: env.ICEPICK_BACKGROUND_DIM_Y || 500
}

export {
  config
}
